"""Symbol tables: symbol_snapshots and symbol_changes."""

import sqlite3


def create_symbol_snapshots_table(conn: sqlite3.Connection, prefix: str = "") -> None:
    """Symbol locations captured at a specific commit.

    Each row records where a code symbol (function, class, etc.) exists
    at the time of a given snapshot.  Used to reconstruct the codebase
    state at any historical point.

    Columns:
        snapshot_id:    FK to snapshots.id.
        qualified_name: Fully qualified symbol name (e.g. "module::Class::method").
        kind:           Symbol type ("function", "class", "variable", etc.).
        file_path:      File containing the symbol.
        line_number:    Line number of the symbol definition.
        signature:      Function/method signature, if applicable.
        class_scope:    Enclosing class name, if the symbol is a method.

    Indexes:
        idx_symbol_snap_snapshot: Join with snapshots.
        idx_symbol_snap_name:    Lookup by qualified_name.
    """
    conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS {prefix}symbol_snapshots (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            snapshot_id    INTEGER NOT NULL REFERENCES {prefix}snapshots(id),
            qualified_name TEXT    NOT NULL,
            kind           TEXT    NOT NULL,
            file_path      TEXT    NOT NULL,
            line_number    INTEGER NOT NULL,
            signature      TEXT,
            class_scope    TEXT
        );
        CREATE INDEX IF NOT EXISTS {prefix}idx_symbol_snap_snapshot ON {prefix}symbol_snapshots(snapshot_id);
        CREATE INDEX IF NOT EXISTS {prefix}idx_symbol_snap_name     ON {prefix}symbol_snapshots(qualified_name);
    """)


def create_symbol_changes_table(conn: sqlite3.Connection, prefix: str = "") -> None:
    """Computed diffs between consecutive symbol snapshots.

    Generated by comparing symbol_snapshots across adjacent commits.
    Records additions, removals, moves, and signature changes.

    Columns:
        snapshot_id:    FK to snapshots.id (the newer commit).
        qualified_name: Symbol that changed.
        change_type:    One of "added", "removed", "moved", "modified".
        old_file_path:  Previous file (for moves/removals).
        new_file_path:  New file (for moves/additions).
        old_line:       Previous line number.
        new_line:       New line number.
        old_signature:  Previous signature.
        new_signature:  New signature.

    Indexes:
        idx_symbol_changes_snapshot: Join with snapshots.
        idx_symbol_changes_name:    Lookup by qualified_name.
    """
    conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS {prefix}symbol_changes (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            snapshot_id    INTEGER NOT NULL REFERENCES {prefix}snapshots(id),
            qualified_name TEXT    NOT NULL,
            change_type    TEXT    NOT NULL,
            old_file_path  TEXT,
            new_file_path  TEXT,
            old_line       INTEGER,
            new_line       INTEGER,
            old_signature  TEXT,
            new_signature  TEXT
        );
        CREATE INDEX IF NOT EXISTS {prefix}idx_symbol_changes_snapshot ON {prefix}symbol_changes(snapshot_id);
        CREATE INDEX IF NOT EXISTS {prefix}idx_symbol_changes_name     ON {prefix}symbol_changes(qualified_name);
    """)


def create_symbol_tables(conn: sqlite3.Connection, prefix: str = "") -> None:
    """Create all symbol tables: symbol_snapshots and symbol_changes."""
    create_symbol_snapshots_table(conn, prefix)
    create_symbol_changes_table(conn, prefix)
